from pathlib import Path


def test_resolver_executor_integration_design_doc_exists():
    doc = Path("docs/memory_resolver_executor_integration_design.md")

    assert doc.exists()


def test_resolver_executor_integration_design_is_design_only():
    text = Path("docs/memory_resolver_executor_integration_design.md").read_text(encoding="utf-8")

    assert "Milestone 112 is design-only." in text
    assert "It must not connect MemoryTargetResolver to MemoryCommandExecutor, IntentRouter, Core, API, HUD, provider prompts, voice, tools, or runtime adapters." in text


def test_resolver_executor_integration_design_defines_future_flow():
    text = Path("docs/memory_resolver_executor_integration_design.md").read_text(encoding="utf-8")

    required = [
        "for correction or delete without memory_id, collect a bounded candidate list",
        "call MemoryTargetResolver with the user query and bounded candidates",
        "handle no_match by returning a user-facing no-match result",
        "handle multiple_candidates by returning bounded candidates for user selection",
        "handle single_safe_match by creating a pending action with selected_memory_id",
        "require confirmation before any correction or delete operation executes",
    ]

    for item in required:
        assert item in text


def test_resolver_executor_integration_design_maps_resolution_outcomes_safely():
    text = Path("docs/memory_resolver_executor_integration_design.md").read_text(encoding="utf-8")

    assert "no_match must not create a pending action." in text
    assert "multiple_candidates must not create an executable pending action." in text
    assert "unsafe_ambiguous_match must not create an executable pending action." in text
    assert "explicit_id_match may create a pending correction or delete action." in text
    assert "single_safe_match may create a pending correction or delete action." in text


def test_resolver_executor_integration_design_requires_bounded_candidates():
    text = Path("docs/memory_resolver_executor_integration_design.md").read_text(encoding="utf-8")

    assert "Candidate lists must be bounded before resolver execution." in text
    assert "MemoryService.list_memories with max_results bounds" in text
    assert "Candidate lists must not be generated by dumping all memory into provider prompts." in text


def test_resolver_executor_integration_design_requires_user_selection_for_multiple_candidates():
    text = Path("docs/memory_resolver_executor_integration_design.md").read_text(encoding="utf-8")

    assert "When multiple candidates exist, the user must choose one candidate explicitly." in text
    assert "The choice must bind to exactly one memory id." in text
    assert "Selection must not execute memory changes immediately." in text


def test_resolver_executor_integration_design_preserves_confirmation_rule():
    text = Path("docs/memory_resolver_executor_integration_design.md").read_text(encoding="utf-8")

    assert "Correction and delete operations must still go through PendingMemoryActionService." in text
    assert "Confirmation must be bound to one concrete pending action." in text
    assert "Confirming a resolver-produced pending action must still call MemoryService with confirmed=True." in text
    assert "Stale pending actions must not execute." in text


def test_resolver_executor_integration_design_preserves_safety_boundaries_and_non_goals():
    text = Path("docs/memory_resolver_executor_integration_design.md").read_text(encoding="utf-8")

    required = [
        "bypass MemoryService",
        "bypass MemoryPolicy",
        "bypass MemoryAuditSink",
        "inject memory into provider prompts",
        "store normal conversation automatically",
        "resolver-to-executor implementation",
        "IntentRouter integration",
        "Core integration",
        "API endpoints",
        "HUD memory panels",
        "semantic/vector search",
        "voice integration",
    ]

    for item in required:
        assert item in text
